version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/" # Ricerca in tutte le cartelle del repository
    schedule:
      interval: "daily" # Controlla gli aggiornamenti ogni giorno

  - package-ecosystem: "bundler"
    directory: "/"
    schedule:
      interval: "daily"

  - package-ecosystem: "composer"
    directory: "/"
    schedule:
      interval: "daily"

  - package-ecosystem: "maven"
    directory: "/"
    schedule:
      interval: "daily"

  - package-ecosystem: "mix"
    directory: "/"
    schedule:
      interval: "daily"

  - package-ecosystem: "cargo"
    directory: "/"
    schedule:
      interval: "daily"

  - package-ecosystem: "gradle"
    directory: "/"
    schedule:
      interval: "daily"

  - package-ecosystem: "nuget"
    directory: "/"
    schedule:
      interval: "daily"

  - package-ecosystem: "gomod"
    directory: "/"
    schedule:
      interval: "daily"

  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "daily"

  - package-ecosystem: "elm"
    directory: "/"
    schedule:
      interval: "daily"

  - package-ecosystem: "gitsubmodule"
    directory: "/"
    schedule:
      interval: "daily"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"

  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "daily"

  - package-ecosystem: "terraform"
    directory: "/"
    schedule:
      interval: "daily"

  - package-ecosystem: "pub"
    directory: "/"
    schedule:
      interval: "daily"

  - package-ecosystem: "swift"
    directory: "/"
    schedule:
      interval: "daily"
